services:
  qc.fair_chewy-orange-foxhound:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-fair_eva:epos-prototype-alpha4
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
