services:
  qc.fair_pasty-amber-pinscher:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-fair_eva:epos-prototype-alpha2
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
