services:
  qc.fair_leaky-razzmatazz-quoll:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-fair_eva:epos-prototype-alpha1
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
